name: News Scraper Pipeline

on:
  schedule:
    # Runs every day at 10pm Pakistani (adjust cron for your timezone if needed)
    - cron: "0 17 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run spiders sequentially
        run: python run_spiders_sequential.py

      - name: Categorize articles
        run: python categorize_articles.py

      - name: Extract perspectives
        run: python extract_perspectives.py
